name: CT-Auction
version: '${version}'
main: xyz.cheesetown.auction.CTAuction
api-version: '1.20'
depend:
  - Vault
commands:
  auction:
    description: 경매에 관련된 명령어를 수행합니다.
    usage: /<command> [등록|보기] [금액] [메시지(없어도 됨)], /<command>
    aliases:
      - 경매